const express = require('express');
const router = express.Router();
const db = require("../model/db.js");

/* GET bidding listing page. */
router.get('/', function(req, res, next) {
  // fetch:
  // 1) Car rides that are confirmed
  // 2) Pending bids
  // 3) List of all unconfirmed car rides that
  //    user has not bidded for
  const mockBids = [
    { date: "1st" },
    { date: "2nd" },
    { date: "3rd" },
    { date: "4rth" },
  ]
  res.render('rider', { rides: mockBids });
});


/* POST Bid creation. */
router.post('/create', function(req, res, next) {
  // change to bid details instead of name
  // const user_name = req.body.name_field;

  /**
   * User bids for the Car Ride
   * The Car Ride entity is identified by the following composite key
   * (driver, date, time, origin, destination)
   * The bid created has the following information to be submitted
   * P_Key (bidder, driver, date, time, origin, destination)
   * others:
   * bidAmount
   * autogenerated information: bidstatus = 'pending'
   */
  const primary_key = {
    bidder : req.body.bidder_field,
    driver : req.body.driver_field,
    date  : req.body.date_field,
    time : req.body.time_field,
    origin : req.body.origin_field,
    destination : req.body.destination_field
  };

  const attribute = {
   bid_amount : req.body.bid_amount_field,
   bid_status : "pending"
  };


  res.redirect('/rider')
});


module.exports = router